import { createAction, props } from '@ngrx/store';
import { ProposedItem } from '../models/batchitemcreation/proposed-item.model';
import { TmsClient } from 'src/app/shared/store/models/tms-client.model';
import { RedmineVersion } from '../models/redmine-version.model';

export const setRedmineProjectsFilterForBatchItemCreationSdCriteria = createAction('[Items Component] Set Redmine Projects Filter For Batch Item Creation Sd Criteria');
export const setSoftDevProjectsFilterForBatchItemCreationSdCriteria = createAction('[Items Component] Set SoftDev Projects Filter For Batch Item Creation Sd Criteria');
export const setRedmineSourceProjectsFilterForBatchItemCreationCriteria = createAction('[Items Component] Set Redmine Source Projects Filter For Batch Item Creation Redmine Criteria');
export const setRedmineTargetProjectsFilterForBatchItemCreationCriteria = createAction('[Items Component] Set Redmine Target Projects Filter For Batch Item Creation Redmine Criteria');
export const setRedmineTargetProjectsFilterForTmsBatchItemCreationCriteria = createAction('[Items Component] Set Redmine Target Projects Filter for Batch Item Creation Tms Criteria');
export const setRedmineUsersByLetterFilterForTmsBatchItemCreationCriteria = createAction('[Items Component] Set User for ITMS  Filter for Batch Item Creation Tms Criteria');
export const setTmsClientsByLetterFilter = createAction('[Items Component] Set Tms Client Filter for Batch Item Creation Tms Criteria');
export const setRedmineTargetProjectsFilterForIdsBatchItemCreationCriteria = createAction('[Items Component] Set Redmine Target Projects Filter for Batch Item Creation Ids Criteria');
export const setBatchItemCreationRecords = createAction('[Items Component] Set Batch Item Creation Records', props<{ proposedItems: ProposedItem[] }>());
export const togglePropsedItemSelection = createAction('[Items Component] Toggle Proposed Item Selection', props<{ proposedItem: ProposedItem }>());
export const toggleAllPropsedItemsSelection = createAction('[Items Component] Toggle All Proposed Items Selection');
export const startBatchItemsCreation = createAction('[Items Component] Start Batch Items Creation');
export const forceEndBatchItemCreation = createAction('[Items Component] Force End Batch Items Creation');
export const continueBatchItemsCreation = createAction('[Items Component] Continue Batch Items Creation');
export const setLinkToCurrentProposedItemAndUnselect = createAction('[Items Component] set Link to current Proposed Item and unselect', props<{ redmineLink: string }>());
export const updateBatchItemCreationFormColumn = createAction('[Items Component] update Columns In Batch Item Grid');
export const dragAndDropBatchItemsCreationColumns = createAction('[Items Component] Drag And Drop Columns in Batch Item Grid', props<{ prevIndex: number, currIndex: number }>());
export const createOneRecordFromBatch = createAction('[Items Component] Create One Record From Batch', props<{ proposedItem: ProposedItem }>());
export const initTmsClients = createAction('[Items Component] Init Tms Ciients');
export const loadTmsClients = createAction('[Items Component] Load Tms Clients', props<{ tmsClients: TmsClient[] }>());
export const initRedmineVersionsForIds = createAction('[Items Component] Init Redmine Versions For Ids', props<{ projectName: string }>());
export const loadRedmineVersionsForIds = createAction('[Items Component] Load Redmine Versions For Ids', props<{ redmineVersions: RedmineVersion[] }>());
export const clearRedmineVersionsForIds = createAction('[Items Component] Clear Redmine Versions For Ids');
export const initRedmineVersionsForTms = createAction('[Items Component] Init Redmine Versions For Tms', props<{ projectName: string }>());
export const loadRedmineVersionsForTms = createAction('[Items Component] Load Redmine Versions For Tms', props<{ redmineVersions: RedmineVersion[] }>());
export const clearRedmineVersionsForTms = createAction('[Items Component] Clear Redmine Versions For Tms');
export const initRedmineVersionsForRedmine = createAction('[Items Component] Init Redmine Versions For Redmine', props<{ projectName: string }>());
export const loadRedmineVersionsForRedmine = createAction('[Items Component] Load Redmine Versions For Redmine', props<{ redmineVersions: RedmineVersion[] }>());
export const clearRedmineVersionsForRedmine = createAction('[Items Component] Clear Redmine Versions For Redmine');
export const initRedmineVersionsForSd = createAction('[Items Component] Init Redmine Versions For Sd', props<{ projectName: string }>());
export const loadRedmineVersionsForSd = createAction('[Items Component] Load Redmine Versions For Sd', props<{ redmineVersions: RedmineVersion[] }>());
export const clearRedmineVersionsForSd = createAction('[Items Component] Clear Redmine Versions For Sd');
export const setBatchItemCreationTabIndex = createAction('[Items Component] Set Tab Index in Batch Item', props<{ index: number }>());
export const setBatchItemCreationSelectedTabIndex = createAction('[Items Component] Set Selected Tab Index in Batch Item', props<{ index: number }>());
